list(APPEND CMAKE_TRY_COMPILE_PLATFORM_VARIABLES INSTALLAMA_OS INSTALLAMA_ARCH)

if(INSTALLAMA_OS STREQUAL "linux")
    set(CMAKE_SYSTEM_NAME "Linux")
elseif(INSTALLAMA_OS STREQUAL "windows")
    set(CMAKE_SYSTEM_NAME "Windows")
elseif(INSTALLAMA_OS STREQUAL "macos")
    set(CMAKE_SYSTEM_NAME "Darwin")
elseif(INSTALLAMA_OS STREQUAL "freebsd")
    set(CMAKE_SYSTEM_NAME "FreeBSD")
else()
    message(FATAL_ERROR "Unknown OS: ${INSTALLAMA_OS}")
endif()

set(CMAKE_SYSTEM_PROCESSOR "${INSTALLAMA_ARCH}")

if(DEFINED ENV{EXTRA_SYSROOT})
    set(CMAKE_FIND_ROOT_PATH "$ENV{EXTRA_SYSROOT}")
endif()

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
