name: Build all cuda
on:
  workflow_dispatch:
  schedule:
    - cron: 0 1 * * 1
jobs:
  dispatch:
    name: ${{ matrix.filter }}
    strategy:
      fail-fast: false
      matrix:
        filter:
          - '50'
          - '61'
          - '70'
          - '75'
          - '80'
          - '86'
          - '89'
          - '90'
          - '100'
          - '120'
          - probe
    uses: ./.github/workflows/build-any-cuda.yml
    with:
      filter: ${{ matrix.filter }}
    secrets: inherit
