name: Build any metal

on:
  workflow_call:
    inputs:
      filter:
        required: true
        type: string
      deploy:
        required: false
        type: boolean
        default: true

  workflow_dispatch:
    inputs:
      filter:
        required: true
        type: string
      deploy:
        description: 'Deploy?'
        required: false
        type: boolean
        default: true

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build ${{ inputs.filter }}
      run: cmake -DFILTER=${{ inputs.filter }} -P build.cmake

    - name: Deploy
      if: ${{ inputs.deploy && vars.HF_REPO != '' }}
      env:
        HF_XET_HIGH_PERFORMANCE: 1
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
        HF_REPO: ${{ vars.HF_REPO }}
      run: |
        pip install -U "huggingface_hub[cli,hf_xet]"
        hf upload "$HF_REPO" output --repo-type=dataset --include "*.zst"
