name: Build all aarch64-macos-metal
on:
  workflow_dispatch:
jobs:
  dispatch:
    name: ${{ matrix.filter }}
    strategy:
      fail-fast: false
      matrix:
        filter:
          - aarch64-macos-metal-m1
          - aarch64-macos-metal-m2
          - aarch64-macos-metal-m3
          - aarch64-macos-metal-m4
    uses: ./.github/workflows/build-any-metal.yml
    with:
      filter: ${{ matrix.filter }}
    secrets: inherit
