name: Build any vulkan

on:
  workflow_call:
    inputs: &common_inputs
      filter:
        type: string
        default: 'vulkan'
      deploy:
        type: boolean
      llamacpp_repo:
        type: string
      llamacpp_version:
        type: string
      boringssl_repo:
        type: string
      boringssl_version:
        type: string

  workflow_dispatch:
    inputs: *common_inputs

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ZIG_VERSION: "0.16.0-dev.3006+94355f192"
      VULKAN_VERSION: "1.4.341.1"

    steps:
      - uses: actions/checkout@v5

      - name: Setup Zig
        run: |
          ZIG="zig-$(uname -m)-linux-$ZIG_VERSION"
          curl -sSf "https://ziglang.org/builds/$ZIG.tar.xz" | tar -Jxf- -C ~
          sudo ln -sf ~/"$ZIG"/zig /usr/bin/zig

      - name: Setup Vulkan
        run: |
          VULKAN="vulkansdk-linux-$(uname -m)-$VULKAN_VERSION"
          curl -sSf "https://sdk.lunarg.com/sdk/download/$VULKAN_VERSION/linux/$VULKAN.tar.xz" | tar -Jxf- -C /opt
          sudo mv /opt/"$VULKAN_VERSION/$(uname -m)" /opt/vulkan-sdk

      - name: Build ${{ inputs.filter }}
        env:
          LLAMACPP_REPO: ${{ inputs.llamacpp_repo }}
          LLAMACPP_VERSION: ${{ inputs.llamacpp_version }}
          BORINGSSL_REPO: ${{ inputs.boringssl_repo }}
          BORINGSSL_VERSION: ${{ inputs.boringssl_version }}
        run: cmake -DFILTER=${{ inputs.filter }} -P build.cmake

      - name: Deploy
        if: ${{ inputs.deploy && vars.HF_REPO != '' }}
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_HUB_DISABLE_PROGRESS_BARS: 1
        run: |
          pip install -U "hf[hf_xet]"
          hf buckets sync output hf://buckets/${{ vars.HF_REPO_BUILD }}/${{ inputs.llamacpp_version || 'test' }}
