name: Build all cpu
on:
  workflow_dispatch:
  schedule:
    - cron: 0 1 * * 1
jobs:
  dispatch:
    name: ${{ matrix.filter }}
    strategy:
      fail-fast: false
      matrix:
        filter:
          - aarch64-linux-cpu-kk
          - aarch64-linux-cpu-lk
          - aarch64-linux-cpu-mk
          - aarch64-linux-cpu-nk
          - aarch64-linux-cpu-qk
          - aarch64-linux-cpu-rk
          - aarch64-linux-cpu-sk
          - aarch64-linux-cpu-uk
          - aarch64-linux-cpu-yk
          - aarch64-linux-cpu-ml
          - aarch64-linux-cpu-ql
          - aarch64-linux-cpu-qm
          - aarch64-linux-cpu-ym
          - aarch64-linux-cpu-qn
          - x86_64-linux-cpu-kkkkk
          - x86_64-linux-cpu-lkkkk
          - x86_64-linux-cpu-mkkkk
          - x86_64-linux-cpu-qkkkk
          - x86_64-linux-cpu-ylkkk
          - x86_64-linux-cpu-qnkkk
          - x86_64-linux-cpu-qrkkk
          - x86_64-linux-cpu-klokk
          - x86_64-linux-cpu-knokk
          - x86_64-linux-cpu-krokk
          - x86_64-linux-cpu-klzkk
          - x86_64-linux-cpu-knzkk
          - x86_64-linux-cpu-krzkk
          - x86_64-linux-cpu-klzlk
          - x86_64-linux-cpu-knzlk
          - x86_64-linux-cpu-krzlk
          - x86_64-linux-cpu-klxmk
          - x86_64-linux-cpu-knxmk
          - x86_64-linux-cpu-krxmk
          - x86_64-linux-cpu-klxnk
          - x86_64-linux-cpu-knxnk
          - x86_64-linux-cpu-krxnk
          - x86_64-linux-cpu-klxok
          - x86_64-linux-cpu-knxok
          - x86_64-linux-cpu-krxok
          - x86_64-linux-cpu-klxpk
          - x86_64-linux-cpu-knxpk
          - x86_64-linux-cpu-krxpk
          - x86_64-linux-cpu-klxqk
          - x86_64-linux-cpu-knxqk
          - x86_64-linux-cpu-krxqk
          - x86_64-linux-cpu-klxrk
          - x86_64-linux-cpu-knxrk
          - x86_64-linux-cpu-krxrk
          - x86_64-linux-cpu-knxrn
          - x86_64-linux-cpu-krxrn
          - aarch64-windows-cpu-kk
          - aarch64-windows-cpu-lk
          - aarch64-windows-cpu-mk
          - aarch64-windows-cpu-nk
          - aarch64-windows-cpu-qk
          - aarch64-windows-cpu-rk
          - aarch64-windows-cpu-sk
          - aarch64-windows-cpu-uk
          - aarch64-windows-cpu-yk
          - aarch64-windows-cpu-ml
          - aarch64-windows-cpu-ql
          - aarch64-windows-cpu-qm
          - aarch64-windows-cpu-ym
          - aarch64-windows-cpu-qn
          - x86_64-windows-cpu-kkkkk
          - x86_64-windows-cpu-lkkkk
          - x86_64-windows-cpu-mkkkk
          - x86_64-windows-cpu-qkkkk
          - x86_64-windows-cpu-ylkkk
          - x86_64-windows-cpu-qnkkk
          - x86_64-windows-cpu-qrkkk
          - x86_64-windows-cpu-klokk
          - x86_64-windows-cpu-knokk
          - x86_64-windows-cpu-krokk
          - x86_64-windows-cpu-klzkk
          - x86_64-windows-cpu-knzkk
          - x86_64-windows-cpu-krzkk
          - x86_64-windows-cpu-klzlk
          - x86_64-windows-cpu-knzlk
          - x86_64-windows-cpu-krzlk
          - x86_64-windows-cpu-klxmk
          - x86_64-windows-cpu-knxmk
          - x86_64-windows-cpu-krxmk
          - x86_64-windows-cpu-klxnk
          - x86_64-windows-cpu-knxnk
          - x86_64-windows-cpu-krxnk
          - x86_64-windows-cpu-klxok
          - x86_64-windows-cpu-knxok
          - x86_64-windows-cpu-krxok
          - x86_64-windows-cpu-klxpk
          - x86_64-windows-cpu-knxpk
          - x86_64-windows-cpu-krxpk
          - x86_64-windows-cpu-klxqk
          - x86_64-windows-cpu-knxqk
          - x86_64-windows-cpu-krxqk
          - x86_64-windows-cpu-klxrk
          - x86_64-windows-cpu-knxrk
          - x86_64-windows-cpu-krxrk
          - x86_64-windows-cpu-knxrn
          - x86_64-windows-cpu-krxrn
          - aarch64-freebsd-cpu-kk
          - aarch64-freebsd-cpu-lk
          - aarch64-freebsd-cpu-mk
          - aarch64-freebsd-cpu-nk
          - aarch64-freebsd-cpu-qk
          - aarch64-freebsd-cpu-rk
          - aarch64-freebsd-cpu-sk
          - aarch64-freebsd-cpu-uk
          - aarch64-freebsd-cpu-yk
          - aarch64-freebsd-cpu-ml
          - aarch64-freebsd-cpu-ql
          - aarch64-freebsd-cpu-qm
          - aarch64-freebsd-cpu-ym
          - aarch64-freebsd-cpu-qn
          - x86_64-freebsd-cpu-kkkkk
          - x86_64-freebsd-cpu-lkkkk
          - x86_64-freebsd-cpu-mkkkk
          - x86_64-freebsd-cpu-qkkkk
          - x86_64-freebsd-cpu-ylkkk
          - x86_64-freebsd-cpu-qnkkk
          - x86_64-freebsd-cpu-qrkkk
          - x86_64-freebsd-cpu-klokk
          - x86_64-freebsd-cpu-knokk
          - x86_64-freebsd-cpu-krokk
          - x86_64-freebsd-cpu-klzkk
          - x86_64-freebsd-cpu-knzkk
          - x86_64-freebsd-cpu-krzkk
          - x86_64-freebsd-cpu-klzlk
          - x86_64-freebsd-cpu-knzlk
          - x86_64-freebsd-cpu-krzlk
          - x86_64-freebsd-cpu-klxmk
          - x86_64-freebsd-cpu-knxmk
          - x86_64-freebsd-cpu-krxmk
          - x86_64-freebsd-cpu-klxnk
          - x86_64-freebsd-cpu-knxnk
          - x86_64-freebsd-cpu-krxnk
          - x86_64-freebsd-cpu-klxok
          - x86_64-freebsd-cpu-knxok
          - x86_64-freebsd-cpu-krxok
          - x86_64-freebsd-cpu-klxpk
          - x86_64-freebsd-cpu-knxpk
          - x86_64-freebsd-cpu-krxpk
          - x86_64-freebsd-cpu-klxqk
          - x86_64-freebsd-cpu-knxqk
          - x86_64-freebsd-cpu-krxqk
          - x86_64-freebsd-cpu-klxrk
          - x86_64-freebsd-cpu-knxrk
          - x86_64-freebsd-cpu-krxrk
          - x86_64-freebsd-cpu-knxrn
          - x86_64-freebsd-cpu-krxrn
    uses: ./.github/workflows/build-any-cpu.yml
    with:
      filter: ${{ matrix.filter }}
    secrets: inherit
