name: Build any cuda

on:
  workflow_call:
    inputs:
      filter:
        required: true
        type: string
      deploy:
        required: false
        type: boolean
        default: true

  workflow_dispatch:
    inputs:
      filter:
        required: true
        type: string
      deploy:
        description: 'Deploy?'
        required: false
        type: boolean
        default: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4

    - name: Install deps
      run: |
        sudo wget -qO /etc/apt/trusted.gpg.d/cuda.asc "https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/3bf863cc.pub"
        sudo tee /etc/apt/sources.list.d/installama.list <<EOF
        deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64 /
        EOF
        sudo apt-get update -y
        sudo apt-get install -y --no-install-recommends cuda-toolkit-12-4
        echo "/usr/local/cuda-12.4/bin" >> $GITHUB_PATH

    - name: Build ${{ inputs.filter }}
      run: cmake -DFILTER=${{ inputs.filter }} -P build.cmake

    - name: Deploy
      if: ${{ inputs.deploy && vars.HF_REPO != '' }}
      env:
        HF_XET_HIGH_PERFORMANCE: 1
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
        HF_REPO: ${{ vars.HF_REPO }}
      run: |
        pip install -U "huggingface_hub[cli,hf_xet]"
        hf upload "$HF_REPO" output --repo-type=dataset --include "*.zst"
