name: Build all rocm
on:
  workflow_dispatch:
  schedule:
    - cron: 0 1 * * 1
jobs:
  dispatch:
    name: ${{ matrix.filter }}
    strategy:
      fail-fast: false
      matrix:
        filter:
          - x86_64-linux-rocm-gfx803
          - x86_64-linux-rocm-gfx900
          - x86_64-linux-rocm-gfx906
          - x86_64-linux-rocm-gfx908
          - x86_64-linux-rocm-gfx90a
          - x86_64-linux-rocm-gfx942
          - x86_64-linux-rocm-gfx1010
          - x86_64-linux-rocm-gfx1011
          - x86_64-linux-rocm-gfx1030
          - x86_64-linux-rocm-gfx1032
          - x86_64-linux-rocm-gfx1100
          - x86_64-linux-rocm-gfx1101
          - x86_64-linux-rocm-gfx1102
          - x86_64-linux-rocm-gfx1151
          - x86_64-linux-rocm-gfx1200
          - x86_64-linux-rocm-gfx1201
          - x86_64-linux-rocm-probe
    uses: ./.github/workflows/build-any-rocm.yml
    with:
      filter: ${{ matrix.filter }}
    secrets: inherit
