name: Build cpu

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Zig
      run: sudo snap install zig --classic --beta

    - name: Build
      run: cmake -DFILTER=cpu -P build.cmake
