name: Build all vulkan
on:
  workflow_dispatch:
  schedule:
    - cron: 0 1 * * 1
jobs:
  dispatch:
    name: ${{ matrix.filter }}
    strategy:
      fail-fast: false
      matrix:
        filter:
          - aarch64-linux-vulkan-kk
          - aarch64-linux-vulkan-lk
          - aarch64-linux-vulkan-mk
          - aarch64-linux-vulkan-nk
          - aarch64-linux-vulkan-qk
          - aarch64-linux-vulkan-rk
          - aarch64-linux-vulkan-sk
          - aarch64-linux-vulkan-uk
          - aarch64-linux-vulkan-yk
          - aarch64-linux-vulkan-ml
          - aarch64-linux-vulkan-ql
          - aarch64-linux-vulkan-qm
          - aarch64-linux-vulkan-ym
          - aarch64-linux-vulkan-qn
          - aarch64-linux-vulkan-probe
          - x86_64-linux-vulkan-kkkkk
          - x86_64-linux-vulkan-lkkkk
          - x86_64-linux-vulkan-mkkkk
          - x86_64-linux-vulkan-qkkkk
          - x86_64-linux-vulkan-ylkkk
          - x86_64-linux-vulkan-qnkkk
          - x86_64-linux-vulkan-qrkkk
          - x86_64-linux-vulkan-klokk
          - x86_64-linux-vulkan-knokk
          - x86_64-linux-vulkan-krokk
          - x86_64-linux-vulkan-klzkk
          - x86_64-linux-vulkan-knzkk
          - x86_64-linux-vulkan-krzkk
          - x86_64-linux-vulkan-klzlk
          - x86_64-linux-vulkan-knzlk
          - x86_64-linux-vulkan-krzlk
          - x86_64-linux-vulkan-klxmk
          - x86_64-linux-vulkan-knxmk
          - x86_64-linux-vulkan-krxmk
          - x86_64-linux-vulkan-klxnk
          - x86_64-linux-vulkan-knxnk
          - x86_64-linux-vulkan-krxnk
          - x86_64-linux-vulkan-klxok
          - x86_64-linux-vulkan-knxok
          - x86_64-linux-vulkan-krxok
          - x86_64-linux-vulkan-klxpk
          - x86_64-linux-vulkan-knxpk
          - x86_64-linux-vulkan-krxpk
          - x86_64-linux-vulkan-klxqk
          - x86_64-linux-vulkan-knxqk
          - x86_64-linux-vulkan-krxqk
          - x86_64-linux-vulkan-klxrk
          - x86_64-linux-vulkan-knxrk
          - x86_64-linux-vulkan-krxrk
          - x86_64-linux-vulkan-knxrn
          - x86_64-linux-vulkan-krxrn
          - x86_64-linux-vulkan-probe
          - aarch64-windows-vulkan-kk
          - aarch64-windows-vulkan-lk
          - aarch64-windows-vulkan-mk
          - aarch64-windows-vulkan-nk
          - aarch64-windows-vulkan-qk
          - aarch64-windows-vulkan-rk
          - aarch64-windows-vulkan-sk
          - aarch64-windows-vulkan-uk
          - aarch64-windows-vulkan-yk
          - aarch64-windows-vulkan-ml
          - aarch64-windows-vulkan-ql
          - aarch64-windows-vulkan-qm
          - aarch64-windows-vulkan-ym
          - aarch64-windows-vulkan-qn
          - aarch64-windows-vulkan-probe
          - x86_64-windows-vulkan-kkkkk
          - x86_64-windows-vulkan-lkkkk
          - x86_64-windows-vulkan-mkkkk
          - x86_64-windows-vulkan-qkkkk
          - x86_64-windows-vulkan-ylkkk
          - x86_64-windows-vulkan-qnkkk
          - x86_64-windows-vulkan-qrkkk
          - x86_64-windows-vulkan-klokk
          - x86_64-windows-vulkan-knokk
          - x86_64-windows-vulkan-krokk
          - x86_64-windows-vulkan-klzkk
          - x86_64-windows-vulkan-knzkk
          - x86_64-windows-vulkan-krzkk
          - x86_64-windows-vulkan-klzlk
          - x86_64-windows-vulkan-knzlk
          - x86_64-windows-vulkan-krzlk
          - x86_64-windows-vulkan-klxmk
          - x86_64-windows-vulkan-knxmk
          - x86_64-windows-vulkan-krxmk
          - x86_64-windows-vulkan-klxnk
          - x86_64-windows-vulkan-knxnk
          - x86_64-windows-vulkan-krxnk
          - x86_64-windows-vulkan-klxok
          - x86_64-windows-vulkan-knxok
          - x86_64-windows-vulkan-krxok
          - x86_64-windows-vulkan-klxpk
          - x86_64-windows-vulkan-knxpk
          - x86_64-windows-vulkan-krxpk
          - x86_64-windows-vulkan-klxqk
          - x86_64-windows-vulkan-knxqk
          - x86_64-windows-vulkan-krxqk
          - x86_64-windows-vulkan-klxrk
          - x86_64-windows-vulkan-knxrk
          - x86_64-windows-vulkan-krxrk
          - x86_64-windows-vulkan-knxrn
          - x86_64-windows-vulkan-krxrn
          - x86_64-windows-vulkan-probe
    uses: ./.github/workflows/build-any-vulkan.yml
    with:
      filter: ${{ matrix.filter }}
    secrets: inherit
