name: Build any vulkan

on:
  workflow_call:
    inputs:
      filter:
        required: true
        type: string
      deploy:
        required: false
        type: boolean
        default: true

  workflow_dispatch:
    inputs:
      filter:
        required: true
        type: string
      deploy:
        description: 'Deploy?'
        required: false
        type: boolean
        default: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ZIG_VERSION: "0.16.0-dev.2535+b5bd49460"
      VULKAN_VERSION: "1.4.341.1"

    steps:
      - uses: actions/checkout@v4

      - name: Setup Zig
        run: |
          ZIG="zig-$(uname -m)-linux-$ZIG_VERSION"
          curl -sSf "https://ziglang.org/builds/$ZIG.tar.xz" | tar -Jxf- -C ~
          sudo ln -sf ~/"$ZIG"/zig /usr/bin/zig

      - name: Setup Vulkan
        run: |
          VULKAN="vulkansdk-linux-$(uname -m)-$VULKAN_VERSION"
          curl -sSf "https://sdk.lunarg.com/sdk/download/$VULKAN_VERSION/linux/$VULKAN.tar.xz" | tar -Jxf- -C /opt
          sudo mv /opt/"$VULKAN_VERSION/$(uname -m)" /opt/vulkan-sdk

      - name: Build ${{ inputs.filter }}
        run: cmake -DFILTER=${{ inputs.filter }} -P build.cmake

      - name: Deploy
        if: ${{ inputs.deploy && vars.HF_REPO != '' }}
        env:
          HF_XET_HIGH_PERFORMANCE: 1
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_REPO: ${{ vars.HF_REPO }}
        run: |
          pip install -U "huggingface_hub[cli,hf_xet]"
          python scripts/upload.py
