name: Cleanup

on:
  workflow_dispatch:
  schedule:
    - cron: 0 6 * * 1

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Cleanup
        if: ${{ vars.HF_REPO != '' }}
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_REPO: ${{ vars.HF_REPO }}
        run: |
          pip install -U "huggingface_hub[cli]"
          python scripts/cleanup.py
