name: Fetch artefacts

on:
  workflow_dispatch:
  schedule:
    - cron: 0 1 * * 1

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Fetch artefacts
        run: python scripts/fetch-artefacts.py

      - name: Deploy
        if: ${{ vars.HF_REPO != '' }}
        env:
          HF_XET_HIGH_PERFORMANCE: 1
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_REPO: ${{ vars.HF_REPO }}
        run: |
          pip install -U "huggingface_hub[cli,hf_xet]"
          python scripts/upload.py
